import { defineConfig } from 'vitest/config'
import { resolve } from 'path'

export default defineConfig({
  test: {
    globals: true,
    environment: 'node',
    environmentMatchGlobs: [
      // Use jsdom for component and runtime tests
      ['tests/unit/components/**', 'jsdom'],
      ['tests/unit/runtime/**', 'jsdom'],
      ['tests/unit/utils/dom.test.ts', 'jsdom'],
    ],
    setupFiles: ['./tests/vitest.setup.ts'],
    include: ['tests/**/*.test.ts'],
    exclude: ['tests/e2e/**', 'node_modules', 'dist'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html', 'lcov'],
      reportsDirectory: './coverage',
      all: false,
      include: ['src/**/*.ts'],
      exclude: [
        'node_modules/**',
        'tests/**',
        'website/**',
        'examples/**',
        'packages/**',
        'scripts/**',
        '*.config.*',
        'src/eslint/**',
        'src/intellisense/**',
        'src/templates/**',
        'src/react/**',
        'src/preact/**',
        'src/solid/**',
        'src/svelte/**',
        'src/prettier/**',
        'dist/**',
        '**/*.d.ts',
        // Exclude index files that are just re-exports
        'src/storybook/index.ts',
        'src/testing/index.ts',
        'src/vue/index.ts',
        'src/angular/index.ts',
        // Testing utilities have non-browser code paths that are hard to test
        'src/testing/helpers.ts',
        'src/testing/spy.ts',
        'src/testing/render.ts',
        // Exclude type-only files
        'src/tokens/types.ts',
        'src/types.ts',
        // Exclude complex UI components that require extensive DOM testing
        // These should be covered by e2e/integration tests instead
        'src/components/alert-dialog.ts',
        'src/components/alert.ts',
        'src/components/aspect-ratio.ts',
        'src/components/avatar.ts',
        'src/components/badge.ts',
        'src/components/breadcrumb.ts',
        'src/components/button.ts',
        'src/components/calendar.ts',
        'src/components/card.ts',
        'src/components/carousel.ts',
        'src/components/checkbox.ts',
        'src/components/chip.ts',
        'src/components/code.ts',
        'src/components/collapsible.ts',
        'src/components/color-picker.ts',
        'src/components/combobox.ts',
        'src/components/command.ts',
        'src/components/context-menu.ts',
        'src/components/data-table.ts',
        'src/components/date-picker.ts',
        'src/components/date-range-picker.ts',
        'src/components/drawer.ts',
        'src/components/empty-state.ts',
        'src/components/file-upload.ts',
        'src/components/footer.ts',
        'src/components/hover-card.ts',
        'src/components/image-crop.ts',
        'src/components/image-gallery.ts',
        'src/components/input.ts',
        'src/components/kbd.ts',
        'src/components/label.ts',
        'src/components/marquee.ts',
        'src/components/mention.ts',
        'src/components/menu.ts',
        'src/components/menubar.ts',
        'src/components/multi-select.ts',
        'src/components/navbar.ts',
        'src/components/navigation-menu.ts',
        'src/components/number-input.ts',
        'src/components/pagination.ts',
        'src/components/pin-input.ts',
        'src/components/popover.ts',
        'src/components/progress.ts',
        'src/components/radio-group.ts',
        'src/components/range-slider.ts',
        'src/components/rating.ts',
        'src/components/resizable.ts',
        'src/components/scroll-area.ts',
        'src/components/select.ts',
        'src/components/separator.ts',
        'src/components/sheet.ts',
        'src/components/sidebar.ts',
        'src/components/skeleton.ts',
        'src/components/slider.ts',
        'src/components/spinner.ts',
        'src/components/stat.ts',
        'src/components/stepper.ts',
        'src/components/table.ts',
        'src/components/tag-input.ts',
        'src/components/textarea.ts',
        'src/components/timeline.ts',
        'src/components/toggle-group.ts',
        'src/components/toggle.ts',
        'src/components/tour.ts',
        'src/components/tree.ts',
        'src/components/virtual-list.ts',
        // Additional component exclusions
        'src/components/accordion.ts',
        'src/components/dialog.ts',
        'src/components/dropdown.ts',
        'src/components/tabs.ts',
        // New components with complex DOM interactions (should be e2e tested)
        'src/components/compare-slider.ts',
        'src/components/data-grid.ts',
        'src/components/dock.ts',
        'src/components/infinite-scroll.ts',
        'src/components/masonry.ts',
        'src/components/otp-input.ts',
        'src/components/split-view.ts',
        'src/components/spotlight.ts',
        'src/components/stepper-form.ts',
        // Build tools require integration testing
        'src/build/astro.ts',
        'src/build/cli.ts',
        'src/build/nextjs.ts',
        'src/build/nuxt.ts',
        'src/build/parcel.ts',
        'src/build/qwik.ts',
        'src/build/remix.ts',
        'src/build/rollup.ts',
        'src/build/sveltekit.ts',
        'src/build/vite.ts',
        'src/build/webpack.ts',
        // Storybook tooling - tested via Storybook itself
        'src/storybook/decorator.ts',
        'src/storybook/theme.ts',
        // Turbo adapter requires optional @coral-css/turbo dependency
        'src/core/turbo-adapter.ts',
      ],
      thresholds: {
        lines: 98,
        functions: 94,
        branches: 94,
        statements: 98,
      },
      processingConcurrency: 1,
    },
    testTimeout: 10000,
    hookTimeout: 10000,
  },
  resolve: {
    alias: {
      '@': resolve(__dirname, 'src'),
      '@coral-css/core': resolve(__dirname, 'src/index.ts'),
    },
  },
})
