/**
 * Config Converter
 *
 * Converts Tailwind CSS configuration to CoralCSS format.
 * @module migration/config-converter
 */

import type { TailwindConfig, CoralConfig } from './types'

/**
 * Convert Tailwind config to CoralCSS config
 */
export function convertTailwindConfig(tailwindConfig: TailwindConfig): CoralConfig {
  const coralConfig: CoralConfig = {}

  // Convert content paths (same format)
  if (tailwindConfig.content) {
    coralConfig.content = tailwindConfig.content
  }

  // Convert dark mode
  if (tailwindConfig.darkMode) {
    if (Array.isArray(tailwindConfig.darkMode)) {
      // ['class', '.dark'] format
      coralConfig.darkMode = 'selector'
    } else {
      coralConfig.darkMode = tailwindConfig.darkMode
    }
  }

  // Convert prefix
  if (tailwindConfig.prefix) {
    coralConfig.prefix = tailwindConfig.prefix
  }

  // Convert theme
  if (tailwindConfig.theme) {
    coralConfig.theme = convertTheme(tailwindConfig.theme)
  }

  return coralConfig
}

/**
 * Convert theme configuration
 */
function convertTheme(tailwindTheme: TailwindConfig['theme']): Record<string, unknown> {
  if (!tailwindTheme) {return {}}

  const coralTheme: Record<string, unknown> = {}

  // Merge base theme and extend
  const baseTheme = { ...tailwindTheme }
  const extendTheme = tailwindTheme.extend || {}

  // Remove extend from base theme object
  delete (baseTheme as Record<string, unknown>).extend

  // Merge colors
  if (baseTheme.colors || extendTheme.colors) {
    coralTheme.colors = {
      ...(baseTheme.colors as Record<string, unknown> || {}),
      ...(extendTheme.colors as Record<string, unknown> || {}),
    }
  }

  // Merge spacing
  if (baseTheme.spacing || extendTheme.spacing) {
    coralTheme.spacing = {
      ...(baseTheme.spacing as Record<string, unknown> || {}),
      ...(extendTheme.spacing as Record<string, unknown> || {}),
    }
  }

  // Merge screens
  if (baseTheme.screens || extendTheme.screens) {
    coralTheme.screens = {
      ...(baseTheme.screens as Record<string, unknown> || {}),
      ...(extendTheme.screens as Record<string, unknown> || {}),
    }
  }

  // Merge fontFamily
  if (baseTheme.fontFamily || extendTheme.fontFamily) {
    coralTheme.fontFamily = {
      ...(baseTheme.fontFamily as Record<string, unknown> || {}),
      ...(extendTheme.fontFamily as Record<string, unknown> || {}),
    }
  }

  // Merge fontSize
  if (baseTheme.fontSize || extendTheme.fontSize) {
    coralTheme.fontSize = {
      ...(baseTheme.fontSize as Record<string, unknown> || {}),
      ...(extendTheme.fontSize as Record<string, unknown> || {}),
    }
  }

  return coralTheme
}

/**
 * Generate CoralCSS config file content
 */
export function generateCoralConfigFile(config: CoralConfig, useWindPreset = false): string {
  const presetImport = useWindPreset
    ? "import { createCoral, windPreset } from '@coral-css/core'"
    : "import { createCoral, coralPreset } from '@coral-css/core'"

  const presetUsage = useWindPreset
    ? `windPreset({
    darkMode: '${config.darkMode || 'class'}',
  })`
    : `coralPreset({
    darkMode: '${config.darkMode || 'class'}',
  })`

  let output = `/**
 * CoralCSS Configuration
 *
 * Generated by CoralCSS Migration Tool
 * https://coralcss.dev
 */

${presetImport}

export default createCoral({
  plugins: ${presetUsage},
`

  // Add content paths
  if (config.content && config.content.length > 0) {
    output += `
  content: [
    ${config.content.map(c => `'${c}'`).join(',\n    ')},
  ],
`
  }

  // Add prefix if present
  if (config.prefix) {
    output += `
  prefix: '${config.prefix}',
`
  }

  // Add theme if present
  if (config.theme && Object.keys(config.theme).length > 0) {
    output += `
  theme: ${JSON.stringify(config.theme, null, 4).replace(/\n/g, '\n  ')},
`
  }

  output += `})
`

  return output
}

/**
 * Parse Tailwind config from string content
 * Note: This is a simplified parser. For complex configs, use proper AST parsing.
 */
export function parseTailwindConfigString(content: string): Partial<TailwindConfig> {
  const config: Partial<TailwindConfig> = {}

  // Extract content array
  const contentMatch = content.match(/content:\s*\[([\s\S]*?)\]/m)
  if (contentMatch) {
    const contentPaths = contentMatch[1]!
      .split(',')
      .map(s => s.trim())
      .filter(s => s.length > 0)
      .map(s => s.replace(/['"]/g, ''))
    config.content = contentPaths
  }

  // Extract darkMode
  const darkModeMatch = content.match(/darkMode:\s*['"]?(class|media)['"]?/)
  if (darkModeMatch) {
    config.darkMode = darkModeMatch[1] as 'class' | 'media'
  }

  // Extract prefix
  const prefixMatch = content.match(/prefix:\s*['"]([^'"]+)['"]/)
  if (prefixMatch) {
    config.prefix = prefixMatch[1]
  }

  // Extract theme colors (simplified)
  const colorsMatch = content.match(/colors:\s*\{([^}]+)\}/)
  if (colorsMatch) {
    try {
      // Simplified color parsing
      const colorEntries = colorsMatch[1]!
        .split(',')
        .map(entry => entry.trim())
        .filter(entry => entry.length > 0)
        .map(entry => {
          const [key, value] = entry.split(':').map(s => s.trim().replace(/['"]/g, ''))
          return [key, value]
        })
        .filter(([key, value]) => key && value)

      if (colorEntries.length > 0) {
        config.theme = {
          extend: {
            colors: Object.fromEntries(colorEntries),
          },
        }
      }
    } catch {
      // Ignore parsing errors for colors
    }
  }

  return config
}

/**
 * Convert PostCSS config
 */
export function convertPostCSSConfig(content: string): string {
  // Replace tailwindcss with @coral-css/postcss
  let newContent = content.replace(
    /['"]?tailwindcss['"]?/g,
    "'@coral-css/postcss'"
  )

  // Replace @tailwindcss/postcss with @coral-css/postcss
  newContent = newContent.replace(
    /'@tailwindcss\/postcss'/g,
    "'@coral-css/postcss'"
  )

  return newContent
}

/**
 * Convert Vite config
 */
export function convertViteConfig(content: string): string {
  // Replace tailwind plugin import
  let newContent = content.replace(
    /import\s+(?:tailwindcss|tailwind)\s+from\s+['"]@tailwindcss\/vite['"]/g,
    "import coral from '@coral-css/core/vite'"
  )

  // Replace plugin usage
  newContent = newContent.replace(
    /tailwindcss\(\)/g,
    'coral()'
  )

  newContent = newContent.replace(
    /tailwind\(\)/g,
    'coral()'
  )

  return newContent
}

/**
 * Get list of config files to migrate
 */
export function getConfigFilesToMigrate(): { source: string; target: string; description: string }[] {
  return [
    {
      source: 'tailwind.config.js',
      target: 'coral.config.js',
      description: 'Main configuration file',
    },
    {
      source: 'tailwind.config.ts',
      target: 'coral.config.ts',
      description: 'TypeScript configuration file',
    },
    {
      source: 'tailwind.config.mjs',
      target: 'coral.config.mjs',
      description: 'ES Module configuration file',
    },
    {
      source: 'postcss.config.js',
      target: 'postcss.config.js',
      description: 'PostCSS configuration (update plugin name)',
    },
    {
      source: 'postcss.config.mjs',
      target: 'postcss.config.mjs',
      description: 'PostCSS ES Module configuration',
    },
  ]
}

/**
 * Generate migration instructions for a config type
 */
export function getMigrationInstructions(configType: 'vite' | 'postcss' | 'tailwind'): string[] {
  switch (configType) {
    case 'vite':
      return [
        "1. Install CoralCSS: npm install @coral-css/core",
        "2. Update vite.config.js:",
        "   - Change: import tailwind from '@tailwindcss/vite'",
        "   - To:     import coral from '@coral-css/core/vite'",
        "3. Update plugins array to use coral() instead of tailwind()",
        "4. Run your dev server to verify: npm run dev",
      ]

    case 'postcss':
      return [
        "1. Install CoralCSS: npm install @coral-css/core",
        "2. Update postcss.config.js:",
        "   - Change: 'tailwindcss' or '@tailwindcss/postcss'",
        "   - To:     '@coral-css/postcss'",
        "3. Update content paths if needed",
        "4. Run your build to verify: npm run build",
      ]

    case 'tailwind':
      return [
        "1. Install CoralCSS: npm install @coral-css/core",
        "2. Create coral.config.js (or coral.config.ts)",
        "3. Import createCoral and coralPreset from '@coral-css/core'",
        "4. Copy your theme customizations",
        "5. Update content paths",
        "6. Remove tailwind.config.js after verifying migration",
      ]

    default:
      return []
  }
}
